# Generated by Django 3.0.8 on 2020-08-24 11:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ecourse_admin', '0002_auto_20200824_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='myvid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentid', models.TextField()),
                ('course_id', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='addcourse',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='addcourse',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='addcourse',
            name='shortdescription',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='addcourse',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='adminlogin',
            name='email',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='adminlogin',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='adminlogin',
            name='password',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='userlogin',
            name='email',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='userlogin',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='userlogin',
            name='password',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='websitedetails',
            name='websitename',
            field=models.CharField(max_length=200),
        ),
    ]
