# Generated by Django 3.0.8 on 2020-08-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecourse_admin', '0003_auto_20200824_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcourse',
            name='status',
            field=models.CharField(default='', max_length=200),
        ),
    ]
