# Generated by Django 3.0.8 on 2020-08-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecourse_admin', '0004_addcourse_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcourse',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
