# Generated by Django 3.0.8 on 2020-08-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecourse_admin', '0005_addcourse_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='videos',
            field=models.FileField(blank=True, upload_to='videos/'),
        ),
    ]
