# Generated by Django 3.0.8 on 2020-08-31 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecourse_admin', '0007_auto_20200827_2159'),
    ]

    operations = [
        migrations.CreateModel(
            name='userprofilepic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentid', models.TextField()),
                ('profile_pic', models.TextField()),
            ],
        ),
    ]
